version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
  admin-db:
    container_name: admin-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/admin-db:/data/db
    networks:
      - admin-network
  admin-db-ui:
    container_name: admin-db-ui
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: admin-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
    links:
      - admin-db
    networks:
      - admin-network
    depends_on:
      - admin-db
  events-db:
    container_name: events-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27018:27017
    volumes:
      - ./docker-volumes/events-db:/data/db
    networks:
      - events-network
  events-db-ui:
    container_name: events-db-ui
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: events-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
    links:
      - events-db
    networks:
      - events-network
    depends_on:
      - events-db
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
    - 9411:9411

networks:
  admin-network:
    driver: bridge
  events-network:
    driver: bridge