version: '3'

services:
  admin-db:
    container_name: admin-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/admin-db:/data/db
    networks:
      - admin-network
  admin-db-ui:
    container_name: admin-db-ui
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: admin-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
    links:
      - admin-db
    networks:
      - admin-network
    depends_on:
      - admin-db

networks:
  admin-network:
    driver: bridge