version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
  admin-db:
    container_name: admin-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/admin-db:/data/db
    networks:
      - admin-network
#  admin-db-ui:
#    container_name: admin-db-ui
#    image: mongo-express
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_SERVER: admin-db
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
#    links:
#      - admin-db
#    networks:
#      - admin-network
#    depends_on:
#      - admin-db
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
    - 9411:9411
#  elk:
#    container_name: elk
#    #image: sebp/elk
#    build: ./docker-volumes/elk/
#    ports:
#      - 5601:5601 # Kibana
#      - 9200:9200 # ElasticSearch
#      - 5044:5044 # LogStash
#    volumes:
#      #- ./docker-volumes/elk/logstash/30-output.conf:/etc/logstash/conf.d/30-output.conf
#      #- ./docker-volumes/elk/logstash/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
#      - ./docker-volumes/elk/elasticsearch:/var/lib/elasticsearch

    # Configuração mínima de memória:
    # wsl -d docker-desktop
    # sysctl -w vm.max_map_count=262144

networks:
  admin-network:
    driver: bridge