eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false

rabbitmq:
  hostName: localhost
  userName: guest
  password: guest
  exchangeName: event-exchange
  queueName: event-queue
  routingKeyName: event-key

elasticsearch:
  host: 34.95.173.42
  port: 9200

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/