eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false

zuul:
  ignored-services: *
  routes:
    admin-service:
      path: /admin/**
      serviceId: admin-service
      strip-prefix: false
    event-producer-service:
      path: /event-producer/**
      serviceId: event-producer-service
      strip-prefix: false

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

logstash:
  host: 34.95.173.42
  port: 5044